# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'box2.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1016, 832)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.radioButton = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton.setGeometry(QtCore.QRect(420, 620, 161, 19))
        self.radioButton.setStyleSheet("QRadioButton::indicator{\n"
"    width:15px;\n"
"    height:15px;\n"
"    color:white;\n"
"    border-radius:8px;\n"
"    border-style: solid;\n"
"    border-width: 1px;\n"
"    border-color: white;\n"
"\n"
"}\n"
"QRadioButton::indicator:checked {\n"
"    background-color:black;\n"
"}\n"
"QRadioButton::indicator:unchecked {\n"
"    background-color:rgb(255, 255, 255);\n"
"}\n"
"")
        self.radioButton.setObjectName("radioButton")
        self.yesorno = QtWidgets.QLabel(self.centralwidget)
        self.yesorno.setGeometry(QtCore.QRect(671, 620, 111, 51))
        self.yesorno.setText("")
        self.yesorno.setObjectName("yesorno")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(-10, 0, 1029, 47))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.dtlb = QtWidgets.QLabel(self.frame)
        self.dtlb.setObjectName("dtlb")
        self.horizontalLayout.addWidget(self.dtlb)
        spacerItem = QtWidgets.QSpacerItem(747, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.loguobtn = QtWidgets.QToolButton(self.frame)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.loguobtn.setFont(font)
        self.loguobtn.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.loguobtn.setAutoRaise(True)
        self.loguobtn.setObjectName("loguobtn")
        self.horizontalLayout.addWidget(self.loguobtn)
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(360, 50, 271, 20))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.line_3 = QtWidgets.QFrame(self.centralwidget)
        self.line_3.setGeometry(QtCore.QRect(670, 50, 271, 20))
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.line_4 = QtWidgets.QFrame(self.centralwidget)
        self.line_4.setGeometry(QtCore.QRect(40, 50, 271, 20))
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.line_5 = QtWidgets.QFrame(self.centralwidget)
        self.line_5.setGeometry(QtCore.QRect(40, 110, 271, 20))
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.line_6 = QtWidgets.QFrame(self.centralwidget)
        self.line_6.setGeometry(QtCore.QRect(360, 110, 271, 20))
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.line_7 = QtWidgets.QFrame(self.centralwidget)
        self.line_7.setGeometry(QtCore.QRect(670, 110, 271, 16))
        self.line_7.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(89, 70, 161, 41))
        self.widget.setObjectName("widget")
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setGeometry(QtCore.QRect(40, 10, 72, 15))
        self.label_2.setObjectName("label_2")
        self.widget_2 = QtWidgets.QWidget(self.centralwidget)
        self.widget_2.setGeometry(QtCore.QRect(410, 70, 161, 41))
        self.widget_2.setObjectName("widget_2")
        self.label_3 = QtWidgets.QLabel(self.widget_2)
        self.label_3.setGeometry(QtCore.QRect(50, 10, 72, 15))
        self.label_3.setObjectName("label_3")
        self.widget_3 = QtWidgets.QWidget(self.centralwidget)
        self.widget_3.setGeometry(QtCore.QRect(720, 70, 161, 41))
        self.widget_3.setObjectName("widget_3")
        self.label_4 = QtWidgets.QLabel(self.widget_3)
        self.label_4.setGeometry(QtCore.QRect(50, 10, 72, 15))
        self.label_4.setObjectName("label_4")
        self.widget_4 = QtWidgets.QWidget(self.centralwidget)
        self.widget_4.setGeometry(QtCore.QRect(40, 140, 271, 231))
        self.widget_4.setObjectName("widget_4")
        self.label_12 = QtWidgets.QLabel(self.widget_4)
        self.label_12.setGeometry(QtCore.QRect(10, 10, 251, 211))
        self.label_12.setText("")
        self.label_12.setObjectName("label_12")
        self.widget_5 = QtWidgets.QWidget(self.centralwidget)
        self.widget_5.setGeometry(QtCore.QRect(39, 390, 271, 41))
        self.widget_5.setObjectName("widget_5")
        self.label_5 = QtWidgets.QLabel(self.widget_5)
        self.label_5.setGeometry(QtCore.QRect(260, 40, 72, 15))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.widget_5)
        self.label_6.setGeometry(QtCore.QRect(91, 10, 81, 20))
        self.label_6.setObjectName("label_6")
        self.widget_6 = QtWidgets.QWidget(self.centralwidget)
        self.widget_6.setGeometry(QtCore.QRect(39, 440, 271, 141))
        self.widget_6.setObjectName("widget_6")
        self.label_9 = QtWidgets.QLabel(self.widget_6)
        self.label_9.setGeometry(QtCore.QRect(21, 9, 241, 131))
        self.label_9.setWordWrap(True)
        self.label_9.setObjectName("label_9")
        self.widget_7 = QtWidgets.QWidget(self.centralwidget)
        self.widget_7.setGeometry(QtCore.QRect(351, 140, 271, 231))
        self.widget_7.setObjectName("widget_7")
        self.label_13 = QtWidgets.QLabel(self.widget_7)
        self.label_13.setGeometry(QtCore.QRect(10, 10, 251, 211))
        self.label_13.setText("")
        self.label_13.setObjectName("label_13")
        self.widget_8 = QtWidgets.QWidget(self.centralwidget)
        self.widget_8.setGeometry(QtCore.QRect(350, 390, 271, 41))
        self.widget_8.setObjectName("widget_8")
        self.label_7 = QtWidgets.QLabel(self.widget_8)
        self.label_7.setGeometry(QtCore.QRect(40, 10, 221, 20))
        self.label_7.setObjectName("label_7")
        self.widget_9 = QtWidgets.QWidget(self.centralwidget)
        self.widget_9.setGeometry(QtCore.QRect(350, 440, 271, 141))
        self.widget_9.setObjectName("widget_9")
        self.label_10 = QtWidgets.QLabel(self.widget_9)
        self.label_10.setGeometry(QtCore.QRect(20, 9, 241, 121))
        self.label_10.setWordWrap(True)
        self.label_10.setObjectName("label_10")
        self.widget_10 = QtWidgets.QWidget(self.centralwidget)
        self.widget_10.setGeometry(QtCore.QRect(661, 140, 271, 231))
        self.widget_10.setObjectName("widget_10")
        self.label_14 = QtWidgets.QLabel(self.widget_10)
        self.label_14.setGeometry(QtCore.QRect(10, 10, 251, 211))
        self.label_14.setText("")
        self.label_14.setObjectName("label_14")
        self.widget_11 = QtWidgets.QWidget(self.centralwidget)
        self.widget_11.setGeometry(QtCore.QRect(660, 390, 271, 41))
        self.widget_11.setObjectName("widget_11")
        self.label_8 = QtWidgets.QLabel(self.widget_11)
        self.label_8.setGeometry(QtCore.QRect(101, 10, 81, 20))
        self.label_8.setObjectName("label_8")
        self.widget_12 = QtWidgets.QWidget(self.centralwidget)
        self.widget_12.setGeometry(QtCore.QRect(660, 440, 271, 141))
        self.widget_12.setObjectName("widget_12")
        self.label_11 = QtWidgets.QLabel(self.widget_12)
        self.label_11.setGeometry(QtCore.QRect(20, 9, 241, 121))
        self.label_11.setWordWrap(True)
        self.label_11.setObjectName("label_11")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(570, 670, 100, 100))
        self.pushButton.setMinimumSize(QtCore.QSize(100, 100))
        self.pushButton.setMaximumSize(QtCore.QSize(100, 100))
        self.pushButton.setStyleSheet("QPushButton{background:qlineargradient(spread:pad, x1:0, y1:1, x2:0, y2:0, \n"
"                              stop:0  rgb(170, 170, 255), stop:0.5 #4169E1, stop:1 \n"
"                              rgb(170, 170, 255));border:0px;border-radius:50px;color:white;}\n"
                                     "QPushButton:hover{ background:qlineargradient(spread:pad, x1:0, y1:1, x2:0, y2:0, \n"
"                              stop:0  #FF66B2, stop:0.5 #660066, stop:1 \n"
"                              #FF66B2);border:0px;border-radius:50px;color:white;}"
                                     "QPushButton:pressed{  background:qlineargradient(spread:pad, x1:0, y1:1, x2:0, y2:0, \n"
"                              stop:0  rgb(170, 170, 255), stop:0.5 #4169E1, stop:1 \n"
"                              rgb(170, 170, 255));border:0px;border-radius:50px;color:white;padding-left:10px; padding-top:10px;}"
"")
        self.pushButton.setObjectName("pushButton")
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setGeometry(QtCore.QRect(190, 710, 150, 26))
        self.progressBar.setMinimumSize(QtCore.QSize(150, 0))
        self.progressBar.setMaximumSize(QtCore.QSize(150, 16777215))
        self.progressBar.setStyleSheet("QProgressBar { border: 2px solid grey; border-radius: 5px; background-color: #FFFFFF; text-align: center;}QProgressBar::chunk {background:QLinearGradient(x1:0,y1:0,x2:2,y2:0,stop:0 #666699,stop:1  #DB7093); }\n"
"")
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.matButton = QtWidgets.QPushButton(self.centralwidget)
        self.matButton.setGeometry(QtCore.QRect(100, 670, 100, 100))
        self.matButton.setMinimumSize(QtCore.QSize(100, 100))
        self.matButton.setMaximumSize(QtCore.QSize(100, 100))
        self.matButton.setStyleSheet("QPushButton{background:qlineargradient(spread:pad, x1:0, y1:1, x2:0, y2:0, \n"
"                              stop:0  rgb(170, 170, 255), stop:0.5 #4169E1, stop:1 \n"
"                              rgb(170, 170, 255));border:0px;border-radius:50px;color:white;}\n"
                                     "QPushButton:hover{ background:qlineargradient(spread:pad, x1:0, y1:1, x2:0, y2:0, \n"
"                              stop:0  #FF66B2, stop:0.5 #660066, stop:1 \n"
"                              #FF66B2);border:0px;border-radius:50px;color:white;}"
                                     "QPushButton:pressed{  background:qlineargradient(spread:pad, x1:0, y1:1, x2:0, y2:0, \n"
"                              stop:0  rgb(170, 170, 255), stop:0.5 #4169E1, stop:1 \n"
"                              rgb(170, 170, 255));border:0px;border-radius:50px;color:white;padding-left:10px; padding-top:10px;}"
"")
        self.matButton.setObjectName("matButton")
        self.txtButton = QtWidgets.QPushButton(self.centralwidget)
        self.txtButton.setGeometry(QtCore.QRect(340, 670, 100, 100))
        self.txtButton.setMinimumSize(QtCore.QSize(100, 100))
        self.txtButton.setMaximumSize(QtCore.QSize(100, 100))
        self.txtButton.setStyleSheet("QPushButton{background:qlineargradient(spread:pad, x1:0, y1:1, x2:0, y2:0, \n"
"                              stop:0  rgb(170, 170, 255), stop:0.5 #4169E1, stop:1 \n"
"                              rgb(170, 170, 255));border:0px;border-radius:50px;color:white;}\n"
                                     "QPushButton:hover{ background:qlineargradient(spread:pad, x1:0, y1:1, x2:0, y2:0, \n"
"                              stop:0  #FF66B2, stop:0.5 #660066, stop:1 \n"
"                              #FF66B2);border:0px;border-radius:50px;color:white;}"
                                     "QPushButton:pressed{  background:qlineargradient(spread:pad, x1:0, y1:1, x2:0, y2:0, \n"
"                              stop:0  rgb(170, 170, 255), stop:0.5 #4169E1, stop:1 \n"
"                              rgb(170, 170, 255));border:0px;border-radius:50px;color:white;padding-left:10px; padding-top:10px;}"
"")
        self.txtButton.setObjectName("txtButton")
        self.progressBar2 = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar2.setGeometry(QtCore.QRect(430, 710, 150, 26))
        self.progressBar2.setMinimumSize(QtCore.QSize(150, 0))
        self.progressBar2.setMaximumSize(QtCore.QSize(150, 16777215))
        self.progressBar2.setStyleSheet("QProgressBar { border: 2px solid grey; border-radius: 5px; background-color: #FFFFFF; text-align: center;}QProgressBar::chunk {background:QLinearGradient(x1:0,y1:0,x2:2,y2:0,stop:0 #666699,stop:1  #DB7093); }\n"
"")
        self.progressBar2.setProperty("value", 24)
        self.progressBar2.setObjectName("progressBar2")
        self.progressBar3 = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar3.setGeometry(QtCore.QRect(660, 710, 150, 26))
        self.progressBar3.setMinimumSize(QtCore.QSize(150, 0))
        self.progressBar3.setMaximumSize(QtCore.QSize(150, 16777215))
        self.progressBar3.setStyleSheet("QProgressBar { border: 2px solid grey; border-radius: 5px; background-color: #FFFFFF; text-align: center;}QProgressBar::chunk {background:QLinearGradient(x1:0,y1:0,x2:2,y2:0,stop:0 #666699,stop:1  #DB7093); }\n"
"")
        self.progressBar3.setProperty("value", 24)
        self.progressBar3.setObjectName("progressBar3")
        self.answerButton = QtWidgets.QPushButton(self.centralwidget)
        self.answerButton.setGeometry(QtCore.QRect(800, 670, 100, 100))
        self.answerButton.setMinimumSize(QtCore.QSize(100, 100))
        self.answerButton.setMaximumSize(QtCore.QSize(100, 100))
        self.answerButton.setStyleSheet("QPushButton{background:qlineargradient(spread:pad, x1:0, y1:1, x2:0, y2:0, \n"
"                              stop:0  rgb(170, 170, 255), stop:0.5 #1D2B56, stop:1 \n"
"                              rgb(170, 170, 255));border:0px;border-radius:50px;color:white;}\n"
"")
        self.answerButton.setObjectName("answerButton")
        self.progressBar.raise_()
        self.progressBar3.raise_()
        self.progressBar2.raise_()
        self.radioButton.raise_()
        self.yesorno.raise_()
        self.frame.raise_()
        self.line_2.raise_()
        self.line_3.raise_()
        self.line_4.raise_()
        self.line_5.raise_()
        self.line_6.raise_()
        self.line_7.raise_()
        self.widget.raise_()
        self.widget_2.raise_()
        self.widget_3.raise_()
        self.widget_4.raise_()
        self.widget_5.raise_()
        self.widget_6.raise_()
        self.widget_7.raise_()
        self.widget_8.raise_()
        self.widget_9.raise_()
        self.widget_10.raise_()
        self.widget_11.raise_()
        self.widget_12.raise_()
        self.pushButton.raise_()
        self.matButton.raise_()
        self.txtButton.raise_()
        self.answerButton.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1016, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.radioButton.setText(_translate("MainWindow", "是否需要GrandNorm"))
        self.dtlb.setText(_translate("MainWindow", "设计"))
        self.loguobtn.setText(_translate("MainWindow", "返回"))
        self.label_2.setText(_translate("MainWindow", "   PR曲线"))
        self.label_3.setText(_translate("MainWindow", " 混淆矩阵"))
        self.label_4.setText(_translate("MainWindow", " ROC/AUC"))
        self.label_5.setText(_translate("MainWindow", "   PR图"))
        self.label_6.setText(_translate("MainWindow", "AP=0.976"))
        self.label_9.setText(_translate("MainWindow", "PR曲线，全称Precision-Recall Curve，是一种常用的分类模型评估工具。其中，Precision（精确率）定义为True Positive（TP）占所有Positive（P）的比例，Recall（召回率）定义为TP占所有True（T）的比例。"))
        self.label_7.setText(_translate("MainWindow", "TP=541 TN=747 FP=13 FN=49"))
        self.label_10.setText(_translate("MainWindow", "混淆矩阵（Confusion Matrix）是衡量分类模型性能的一种常用方法。在二元分类问题中，混淆矩阵是一个2x2的矩阵，用于表示实际类别和预测类别的四种情况，分别是真正例（TP）、真负例（TN）、假正例（FP）和假负例（FN）"))
        self.label_8.setText(_translate("MainWindow", "AUC=0.98"))
        self.label_11.setText(_translate("MainWindow", "ROC曲线和AUC指标常用于评估二分类模型的性能。ROC曲线是以真正率（True Positive Rate）为纵坐标，假正率（False Positive Rate）为横坐标绘制出的曲线。"))
        self.pushButton.setText(_translate("MainWindow", "预测"))
        self.matButton.setText(_translate("MainWindow", "上传.mat文件"))
        self.txtButton.setText(_translate("MainWindow", "上传.txt文件"))
        self.answerButton.setText(_translate("MainWindow", "结果"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
