# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Dynamic_display.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1290, 787)
        Form.setMouseTracking(True)
        Form.setStyleSheet("QPushButton{\n"
"    background-color:#169bd5;\n"
"    color:rgb(255, 255, 255);\n"
"    border:2px solid #169bd5;\n"
"    border-radius:5px;\n"
"}\n"
"QPushButton:pressed{\n"
"    padding-top:5px;\n"
"    padding-left:5px;\n"
"}\n"
"*{font: 12pt \"黑体\";\n"
"background-color: rgb(255, 255, 255);\n"
"}")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        spacerItem = QtWidgets.QSpacerItem(1260, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_3.addItem(spacerItem)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.label = QtWidgets.QLabel(Form)
        self.label.setStyleSheet("font: 24pt \"黑体\";")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.horizontalLayout.setStretch(0, 1)
        self.horizontalLayout.setStretch(1, 1)
        self.horizontalLayout.setStretch(2, 1)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        spacerItem3 = QtWidgets.QSpacerItem(1260, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_3.addItem(spacerItem3)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem4)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem5)
        self.horizontalLayout_2.setStretch(0, 2)
        self.horizontalLayout_2.setStretch(1, 2)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        spacerItem6 = QtWidgets.QSpacerItem(1260, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_3.addItem(spacerItem6)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.horizontalLayout_3.addItem(spacerItem7)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem8 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem8)
        self.btn_left = QtWidgets.QPushButton(Form)
        self.btn_left.setMinimumSize(QtCore.QSize(30, 150))
        self.btn_left.setMaximumSize(QtCore.QSize(30, 150))
        self.btn_left.setObjectName("btn_left")
        self.verticalLayout.addWidget(self.btn_left)
        spacerItem9 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem9)
        self.verticalLayout.setStretch(0, 1)
        self.verticalLayout.setStretch(1, 1)
        self.verticalLayout.setStretch(2, 1)
        self.horizontalLayout_3.addLayout(self.verticalLayout)
        spacerItem10 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.horizontalLayout_3.addItem(spacerItem10)
        self.picture_show = QtWidgets.QWidget(Form)
        self.picture_show.setMinimumSize(QtCore.QSize(1080, 469))
        self.picture_show.setMaximumSize(QtCore.QSize(1080, 469))
        self.picture_show.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.picture_show.setStyleSheet("#picture_show{\n"
"border:2px solid #169bd5;\n"
"border-radius:5px;\n"
"}")
        self.picture_show.setObjectName("picture_show")
        self.label_3 = QtWidgets.QLabel(self.picture_show)
        self.label_3.setGeometry(QtCore.QRect(220, 80, 691, 121))
        self.label_3.setStyleSheet("font: 18pt \"幼圆\";")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.picture_show)
        self.label_4.setGeometry(QtCore.QRect(210, 190, 751, 111))
        self.label_4.setStyleSheet("font: 18pt \"幼圆\";")
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_3.addWidget(self.picture_show)
        spacerItem11 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.horizontalLayout_3.addItem(spacerItem11)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        spacerItem12 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem12)
        self.btn_right = QtWidgets.QPushButton(Form)
        self.btn_right.setMinimumSize(QtCore.QSize(30, 150))
        self.btn_right.setMaximumSize(QtCore.QSize(30, 150))
        self.btn_right.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btn_right.setObjectName("btn_right")
        self.verticalLayout_2.addWidget(self.btn_right)
        spacerItem13 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem13)
        self.horizontalLayout_3.addLayout(self.verticalLayout_2)
        spacerItem14 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.horizontalLayout_3.addItem(spacerItem14)
        self.horizontalLayout_3.setStretch(0, 1)
        self.horizontalLayout_3.setStretch(1, 1)
        self.horizontalLayout_3.setStretch(2, 1)
        self.horizontalLayout_3.setStretch(4, 1)
        self.horizontalLayout_3.setStretch(5, 1)
        self.horizontalLayout_3.setStretch(6, 1)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        spacerItem15 = QtWidgets.QSpacerItem(1260, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_3.addItem(spacerItem15)
        self.Sidebar = QtWidgets.QWidget(Form)
        self.Sidebar.setMouseTracking(True)
        self.Sidebar.setStyleSheet("QToolButton{\n"
"    background-color:#169bd5;\n"
"    color:rgb(255, 255, 255);\n"
"    border:2px solid #169bd5;\n"
"    border-radius:5px;\n"
"}\n"
"QToolButton:pressed{\n"
"    padding-top:5px;\n"
"    padding-left:5px;\n"
"}\n"
"*{font: 12pt \"黑体\";}")
        self.Sidebar.setObjectName("Sidebar")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.Sidebar)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem16 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem16)
        self.btn1 = QtWidgets.QToolButton(self.Sidebar)
        self.btn1.setMinimumSize(QtCore.QSize(100, 30))
        self.btn1.setMaximumSize(QtCore.QSize(100, 30))
        self.btn1.setMouseTracking(True)
        self.btn1.setObjectName("btn1")
        self.horizontalLayout_4.addWidget(self.btn1)
        spacerItem17 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem17)
        self.btn2 = QtWidgets.QToolButton(self.Sidebar)
        self.btn2.setMinimumSize(QtCore.QSize(100, 30))
        self.btn2.setMaximumSize(QtCore.QSize(100, 30))
        self.btn2.setMouseTracking(True)
        self.btn2.setObjectName("btn2")
        self.horizontalLayout_4.addWidget(self.btn2)
        spacerItem18 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem18)
        self.btn3 = QtWidgets.QToolButton(self.Sidebar)
        self.btn3.setMinimumSize(QtCore.QSize(100, 30))
        self.btn3.setMaximumSize(QtCore.QSize(100, 30))
        self.btn3.setMouseTracking(True)
        self.btn3.setObjectName("btn3")
        self.horizontalLayout_4.addWidget(self.btn3)
        spacerItem19 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem19)
        self.btn4 = QtWidgets.QToolButton(self.Sidebar)
        self.btn4.setMinimumSize(QtCore.QSize(100, 30))
        self.btn4.setMaximumSize(QtCore.QSize(100, 30))
        self.btn4.setMouseTracking(True)
        self.btn4.setObjectName("btn4")
        self.horizontalLayout_4.addWidget(self.btn4)
        spacerItem20 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem20)
        self.horizontalLayout_4.setStretch(0, 2)
        self.horizontalLayout_4.setStretch(2, 1)
        self.horizontalLayout_4.setStretch(3, 1)
        self.horizontalLayout_4.setStretch(4, 1)
        self.horizontalLayout_4.setStretch(5, 1)
        self.horizontalLayout_4.setStretch(6, 1)
        self.horizontalLayout_4.setStretch(7, 1)
        self.horizontalLayout_4.setStretch(8, 2)
        self.verticalLayout_3.addWidget(self.Sidebar)
        spacerItem21 = QtWidgets.QSpacerItem(1260, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_3.addItem(spacerItem21)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "阿尔兹海默病变化过程动态展示"))
        self.btn_left.setText(_translate("Form", "<"))
        self.label_3.setText(_translate("Form", "点击下方按钮选择动态展示相应阿尔兹海默病信息"))
        self.label_4.setText(_translate("Form", "点击左右两边按钮按时间展示阿尔兹海默病动态变化"))
        self.btn_right.setText(_translate("Form", ">"))
        self.btn1.setText(_translate("Form", "大脑变化1"))
        self.btn2.setText(_translate("Form", "大脑变化2"))
        self.btn3.setText(_translate("Form", "身体变化1"))
        self.btn4.setText(_translate("Form", "身体变化2"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
