# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'rumor_mill.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1052, 717)
        Form.setStyleSheet("*{font: 12pt \"黑体\";}\n"
"#frame{\n"
"    border-image: url(:/qipao/bg.PNG);\n"
"}\n"
"")
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.btn4 = QtWidgets.QPushButton(self.frame)
        self.btn4.setGeometry(QtCore.QRect(20, 120, 200, 200))
        self.btn4.setMinimumSize(QtCore.QSize(200, 200))
        self.btn4.setMaximumSize(QtCore.QSize(400, 400))
        self.btn4.setStyleSheet("border-image: url(:/qipao/qipao.png);\n"
"background-color: rgba(0,0, 0, 0);")
        self.btn4.setObjectName("btn4")
        self.btn3 = QtWidgets.QPushButton(self.frame)
        self.btn3.setGeometry(QtCore.QRect(220, 30, 200, 200))
        self.btn3.setMinimumSize(QtCore.QSize(200, 200))
        self.btn3.setMaximumSize(QtCore.QSize(400, 400))
        self.btn3.setStyleSheet("border-image: url(:/qipao/qipao.png);\n"
"background-color: rgba(0,0, 0, 0);")
        self.btn3.setObjectName("btn3")
        self.btn7 = QtWidgets.QPushButton(self.frame)
        self.btn7.setGeometry(QtCore.QRect(420, 30, 200, 200))
        self.btn7.setMinimumSize(QtCore.QSize(200, 200))
        self.btn7.setMaximumSize(QtCore.QSize(400, 400))
        self.btn7.setStyleSheet("border-image: url(:/qipao/qipao.png);\n"
"background-color: rgba(0,0, 0, 0);")
        self.btn7.setObjectName("btn7")
        self.btn5 = QtWidgets.QPushButton(self.frame)
        self.btn5.setGeometry(QtCore.QRect(680, 450, 200, 200))
        self.btn5.setMinimumSize(QtCore.QSize(200, 200))
        self.btn5.setMaximumSize(QtCore.QSize(400, 400))
        self.btn5.setStyleSheet("border-image: url(:/qipao/qipao.png);\n"
"background-color: rgba(0,0, 0, 0);")
        self.btn5.setObjectName("btn5")
        self.btn6 = QtWidgets.QPushButton(self.frame)
        self.btn6.setGeometry(QtCore.QRect(360, 320, 221, 201))
        self.btn6.setMinimumSize(QtCore.QSize(200, 200))
        self.btn6.setMaximumSize(QtCore.QSize(400, 400))
        self.btn6.setStyleSheet("border-image: url(:/qipao/qipao.png);\n"
"background-color: rgba(0,0, 0, 0);")
        self.btn6.setObjectName("btn6")
        self.btn2 = QtWidgets.QPushButton(self.frame)
        self.btn2.setGeometry(QtCore.QRect(100, 340, 200, 200))
        self.btn2.setMinimumSize(QtCore.QSize(200, 200))
        self.btn2.setMaximumSize(QtCore.QSize(400, 400))
        self.btn2.setStyleSheet("border-image: url(:/qipao/qipao.png);\n"
"background-color: rgba(0,0, 0, 0);")
        self.btn2.setObjectName("btn2")
        self.btn1 = QtWidgets.QPushButton(self.frame)
        self.btn1.setGeometry(QtCore.QRect(640, 80, 200, 200))
        self.btn1.setMinimumSize(QtCore.QSize(200, 200))
        self.btn1.setMaximumSize(QtCore.QSize(400, 400))
        self.btn1.setStyleSheet("border-image: url(:/qipao/qipao.png);\n"
"background-color: rgba(0,0, 0, 0);\n"
"")
        self.btn1.setObjectName("btn1")
        self.refresh_btn = QtWidgets.QPushButton(self.frame)
        self.refresh_btn.setGeometry(QtCore.QRect(930, 30, 81, 41))
        self.refresh_btn.setStyleSheet("QPushButton{\n"
"    \n"
"    border-image: url(:/qipao/btn.png);\n"
"    background-color:rgb(255, 255, 255);\n"
"    color:rgb(0, 0, 0);\n"
"    border-radius:5px;\n"
"}\n"
"QPushButton:pressed{\n"
"    padding-top:5px;\n"
"    padding-left:5px;\n"
"}")
        self.refresh_btn.setObjectName("refresh_btn")
        self.verticalLayout.addWidget(self.frame)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.btn4.setText(_translate("Form", "PushButton"))
        self.btn3.setText(_translate("Form", "PushButton"))
        self.btn7.setText(_translate("Form", "PushButton"))
        self.btn5.setText(_translate("Form", "PushButton"))
        self.btn6.setText(_translate("Form", "PushButton"))
        self.btn2.setText(_translate("Form", "PushButton"))
        self.btn1.setText(_translate("Form", "PushButton"))
        self.refresh_btn.setText(_translate("Form", "刷新"))
import images_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
